### PR TITLE
2024-10-23-sigmoid-and-softmax

### PR DESCRIPTION
**Pull request by sigmoidandsoftmax**

### CODE REVIEW

**Comment by busycalibrating** [comment]
Hi, thanks for your submission! I believe we fixed our pipeline - could you **please sync your fork to update the github actions files in your repository**, and hopefully that should auto trigger the build process.  

If you have any other issues, please consult our updated [pull request checklist](https://github.com/iclr-blogposts/2025/blob/main/.github/pull_request_template.md):

## Checklist before opening a PR

- [ ] I am opening a pull request against the `main` branch of the `2025` repo.
- [ ] My post and all associated references to it are all **lowercase**, i.e

        2025-04-28-Sample-Test.md               -> 2025-04-28-sample-test.md
        assets/img/2025-04-28-Sample-Test/ 	  -> assets/img/2025-04-28-sample-test/
- [ ] The title of my PR is exactly the name of my markdown file
    - i.e. `_posts/2025-04-28-[submission-name].md` would require a PR name `2025-04-28-[submission-name]` 
- [ ] I have **anonymized** my post: my author's list is `Anonymous`, and there is no potential
    content which can reveal my/my collaborators identities.
- [ ] My post matches the formatting requirements, including (but not limited to):
    - [ ] I have **ONLY MODIFIED** files in the following locations (failure to do so will result in 
        your PR automatically being closed!):
        - a Markdown (or HTML) file in `_posts/` with the format `_posts/2025-04-28-[submission-name].md` (or `.html`)
        - static image assets added to `assets/img/2025-04-28-[submission-name]/`
        - interactive HTML figures added  to `assets/html/2025-04-28-[submission-name]/`
        - citations in a bibtex file in `assets/bibliography/2025-04-28-[submission-name].bib`
    - [ ] I have a short 2-3 sentence abstract in the `description` field of my front-matter 
    - [ ] I have a table of contents, formatted using the `toc` field of my front-matter
    - [ ] My bibliography is correctly formatted, using a `.bibtex` file as per the sample post

---

Thanks a lot for your patience and please tag me if you need any more help!

**Comment by sigmoidandsoftmax** [comment]
Please merge.

**Comment by busycalibrating** [comment]
There seem to be quite a few changes to the core config files that shouldn't be modified - I would suggest either re-basing to undo all prohibited changes, or if its easier, just closing this PR, creating a new fork off of the latest version of our main branch and just add in the new changes directly without touching any of the other files.

**Comment by busycalibrating** [comment]
Sorry I'm not sure what you mean, does the local build fail?

**Comment by sigmoidandsoftmax** [comment]
yes

**Comment by busycalibrating** [comment]
Are you using the docker image?

**Comment by sigmoidandsoftmax** [comment]
yes

**Comment by busycalibrating** [comment]
Strange, don't think I've come across such an issue. Could you pull a fresh copy of a clean repo somewhere else and just try to run the build script again? You could also clean up your old docker images just to be sure there are no issues there.

**Comment by sigmoidandsoftmax** [comment]
same.

Liquid Exception: Could not find post "2025-04-28-distill-example" in tag 'post_url'. Make sure the post exists and the name is correct. in _pages/about.md
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Could not find post "2025-04-28-distill-example" in tag 'post_url'. Make sure the post exists and the name is correct.

**Comment by busycalibrating** [comment]
You might be missing a `--future` flag with your jekyll commands, i.e. `bundle exec jekyll serve --future`

**Comment by sigmoidandsoftmax** [comment]
Yes. This fix the issue. Thanks.

**Pull request closed without merging**
