### PR TITLE
2025-04-28-immortal

### PR DESCRIPTION
**Pull request by chungimungi**
## Checklist before opening a PR
* [x]  I am opening a pull request against the `main` branch of the `2025` repo.
* [x]  The title of my PR is exactly the name of my markdown file
 
* i.e. `_posts/2025-04-28-[SUBMISSION NAME].md` would require a PR name `2025-04-28-[SUBMISSION NAME]`
* [x]  I have **anonymized** my post: my author's list is `Anonymous`, and there is no potential
content which can reveal my/my collaborators identities.
* [x]  My post matches the formatting requirements, including (but not limited to):

* [x]  I have **ONLY MODIFIED** files in the following locations (failure to do so will result in
your PR automatically being closed!):

* a Markdown (or HTML) file in `_posts/` with the format `_posts/2025-04-28-[SUBMISSION NAME].md` (or `.html`)
* static image assets added to `assets/img/2025-04-28-[SUBMISSION NAME]/`
* interactive HTML figures added  to `assets/html/2025-04-28-[SUBMISSION NAME]/`
* citations in a bibtex file in `assets/bibliography/2025-04-28-[SUBMISSION NAME].bib`
* [x]  I have a short 2-3 sentence abstract in the `description` field of my front-matter
* [x]  I have a table of contents, formatted using the `toc` field of my front-matter
* [x]  My bibliography is correctly formatted, using a `.bibtex` file as per the sample post

## Any other comments

### CODE REVIEW

**Comment by chungimungi** [comment]
> ## OpenReview Submission Thread
> ## Checklist before opening a PR
> * [x]  I am opening a pull request against the `main` branch of the `2025` repo.
> * [x]  The title of my PR is exactly the name of my markdown file
>   
>   * i.e. `_posts/2025-04-28-[SUBMISSION NAME].md` would require a PR name `2025-04-28-[SUBMISSION NAME]`
> * [x]  I have **anonymized** my post: my author's list is `Anonymous`, and there is no potential
>   content which can reveal my/my collaborators identities.
> * [x]  My post matches the formatting requirements, including (but not limited to):
>   
>   * [x]  I have **ONLY MODIFIED** files in the following locations (failure to do so will result in
>     your PR automatically being closed!):
>     
>     * a Markdown (or HTML) file in `_posts/` with the format `_posts/2025-04-28-[SUBMISSION NAME].md` (or `.html`)
>     * static image assets added to `assets/img/2025-04-28-[SUBMISSION NAME]/`
>     * interactive HTML figures added  to `assets/html/2025-04-28-[SUBMISSION NAME]/`
>     * citations in a bibtex file in `assets/bibliography/2025-04-28-[SUBMISSION NAME].bib`
>   * [x]  I have a short 2-3 sentence abstract in the `description` field of my front-matter
>   * [x]  I have a table of contents, formatted using the `toc` field of my front-matter
>   * [x]  My bibliography is correctly formatted, using a `.bibtex` file as per the sample post
> 
> ## Any other comments

**Comment by chungimungi** [comment]
@busycalibrating What seems to be the problem here ?

**Comment by busycalibrating** [comment]
I'm not 100% sure but if you deleted a file in order to create your post, you'll need to do a git rebase to make sure you preserve the original git history. 

The easiest way of doing this (well, at least in terms of avoiding actually doing a rebase) is instead of doing a rebase, you can create a new fork and add in your new files on top of a fresh repo.

**Comment by chungimungi** [comment]
The initial commit was with no files deleted, although the second error that popped up was due to me deleting ```the distill-example.md```. Once i readded it the second error went and the same issue persisted. Let me check with a new fork.

**Pull request closed without merging**
